import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import PageTransition from "@/components/PageTransition";

const inter = Inter({
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased h-full",
          inter.className
        )}>
       
       <div>
        <SidebarProvider>
        <AppSidebar />
        <SidebarTrigger />
        <div className="">
          <PageTransition>
            {children}
          </PageTransition>
        </div>
        </SidebarProvider>
       </div>
      </body>
    </html>
  );
}




