import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contexts/auth-context";
import { AuthGuard } from "@/components/auth-guard";
import { AuthenticatedLayout } from "@/components/authenticated-layout";

const inter = Inter({
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Link Financer",
  description: "Generated by Link System.LTDA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning className="h-full">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased h-full",
          inter.className,
          geistSans.variable,
          geistMono.variable
        )}
      >
        <AuthProvider>
          <AuthGuard>
            <AuthenticatedLayout>
             
              {children}
            </AuthenticatedLayout>
            <Toaster position="top-right" richColors />
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
